name: "base"
env:
  prod:
    debug: false
  dev:
    debug: true
  local:
    debug: true

auth:
  secret_key: "your-super-secret-key"
  algorithm: "HS256"
  token_expire_seconds: 3600
  root_user: "__ROOT_USER__"
  root_password: "__ROOT_PASSWORD__"

logger:
  level: "INFO"
